version: '2'
services:
  service:
    extends:
      file: ./service.yml
      service: service
    depends_on:
      - consul
    links:
      - consul

  consul:
    extends:
      file: ./core-services/services.yml
      service: consul_service

  gateway:
    extends:
      file: ./core-services/services.yml
      service: fabio_service
    links:
      - consul
